-- CreateTable (only if not exists)
CREATE TABLE IF NOT EXISTS `ADMIN_VISION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADMIN_EMP_CODE` VARCHAR(64) NOT NULL,
    `DEPT_PATH` VARCHAR(512) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE INDEX `ADMIN_VISION_ADMIN_EMP_CODE_DEPT_PATH_key`(`ADMIN_EMP_CODE`, `DEPT_PATH`),
    INDEX `ADMIN_VISION_ADMIN_EMP_CODE_idx`(`ADMIN_EMP_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey (only if constraint doesn't exist)
SET @exist := (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_SCHEMA = DATABASE() 
               AND TABLE_NAME = 'ADMIN_VISION' 
               AND CONSTRAINT_NAME = 'ADMIN_VISION_ADMIN_EMP_CODE_fkey');
SET @sqlstmt := IF(@exist = 0, 
    'ALTER TABLE `ADMIN_VISION` ADD CONSTRAINT `ADMIN_VISION_ADMIN_EMP_CODE_fkey` FOREIGN KEY (`ADMIN_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE',
    'SELECT 1');
PREPARE stmt FROM @sqlstmt;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;