/*
  Warnings:

  - The values [PR-PR] on the enum `BOOKING_PLAN_DR_TYPE` will be removed. If these variants are still used in the database, this will fail.
  - The values [Augent] on the enum `MEETING_TYPE_MODE_THRESHOLD_MEETING_TYPE` will be removed. If these variants are still used in the database, this will fail.
  - The values [Augent] on the enum `MEETING_TYPE_MODE_THRESHOLD_MEETING_TYPE` will be removed. If these variants are still used in the database, this will fail.
  - The primary key for the `USER_ROLE` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to drop the `ADMIN_VISION` table. If the table is not empty, all the data it contains will be lost.
  - Made the column `MEETING_TYPE` on table `BOOKING_PLAN` required. This step will fail if there are existing NULL values in that column.

*/
-- DropForeignKey
ALTER TABLE `ADMIN_VISION` DROP FOREIGN KEY `ADMIN_VISION_ADMIN_EMP_CODE_fkey`;

-- DropForeignKey
ALTER TABLE `BOOKING_PLAN` DROP FOREIGN KEY `fk_booking_language`;

-- DropForeignKey
ALTER TABLE `BOOKING_PLAN` DROP FOREIGN KEY `fk_booking_selected_interpreter`;

-- AlterTable
ALTER TABLE `BOOKING_PLAN` MODIFY `DR_TYPE` ENUM('DR-PR', 'DR-k', 'DR-II', 'DR-I', 'Other') NULL,
    MODIFY `MEETING_TYPE` ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL;

-- AlterTable
ALTER TABLE `MEETING_TYPE_MODE_THRESHOLD` MODIFY `MEETING_TYPE` ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL;

-- AlterTable
ALTER TABLE `MEETING_TYPE_PRIORITY` ADD COLUMN `ENVIRONMENT_ID` INTEGER NULL,
    MODIFY `MEETING_TYPE` ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL;

-- AlterTable
ALTER TABLE `USER_ROLE` DROP PRIMARY KEY,
    MODIFY `ROLE_CODE` ENUM('ADMIN', 'INTERPRETER', 'SUPER_ADMIN') NOT NULL,
    ADD PRIMARY KEY (`USER_ID`, `ROLE_CODE`);

-- DropTable
DROP TABLE `ADMIN_VISION`;

-- CreateTable
CREATE TABLE `ENVIRONMENT` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL,

    UNIQUE INDEX `ENVIRONMENT_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ENVIRONMENT_CENTER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ENVIRONMENT_ID` INTEGER NOT NULL,
    `CENTER` VARCHAR(128) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ENVIRONMENT_CENTER_ENVIRONMENT_ID_idx`(`ENVIRONMENT_ID`),
    UNIQUE INDEX `ENVIRONMENT_CENTER_CENTER_key`(`CENTER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ENVIRONMENT_ADMIN` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ENVIRONMENT_ID` INTEGER NOT NULL,
    `ADMIN_EMP_CODE` VARCHAR(64) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ENVIRONMENT_ADMIN_ADMIN_EMP_CODE_idx`(`ADMIN_EMP_CODE`),
    UNIQUE INDEX `ENVIRONMENT_ADMIN_ENVIRONMENT_ID_ADMIN_EMP_CODE_key`(`ENVIRONMENT_ID`, `ADMIN_EMP_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ENVIRONMENT_INTERPRETER` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ENVIRONMENT_ID` INTEGER NOT NULL,
    `INTERPRETER_EMP_CODE` VARCHAR(64) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ENVIRONMENT_INTERPRETER_INTERPRETER_EMP_CODE_idx`(`INTERPRETER_EMP_CODE`),
    UNIQUE INDEX `ENVIRONMENT_INTERPRETER_ENVIRONMENT_ID_INTERPRETER_EMP_CODE_key`(`ENVIRONMENT_ID`, `INTERPRETER_EMP_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_LANGUAGE_CODE_fkey` FOREIGN KEY (`LANGUAGE_CODE`) REFERENCES `LANGUAGE`(`CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_SELECTED_INTERPRETER_EMP_CODE_fkey` FOREIGN KEY (`SELECTED_INTERPRETER_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEETING_TYPE_PRIORITY` ADD CONSTRAINT `MEETING_TYPE_PRIORITY_ENVIRONMENT_ID_fkey` FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENVIRONMENT_CENTER` ADD CONSTRAINT `ENVIRONMENT_CENTER_ENVIRONMENT_ID_fkey` FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENVIRONMENT_ADMIN` ADD CONSTRAINT `ENVIRONMENT_ADMIN_ENVIRONMENT_ID_fkey` FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENVIRONMENT_ADMIN` ADD CONSTRAINT `ENVIRONMENT_ADMIN_ADMIN_EMP_CODE_fkey` FOREIGN KEY (`ADMIN_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENVIRONMENT_INTERPRETER` ADD CONSTRAINT `ENVIRONMENT_INTERPRETER_ENVIRONMENT_ID_fkey` FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENVIRONMENT_INTERPRETER` ADD CONSTRAINT `ENVIRONMENT_INTERPRETER_INTERPRETER_EMP_CODE_fkey` FOREIGN KEY (`INTERPRETER_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- RenameIndex
ALTER TABLE `BOOKING_PLAN` RENAME INDEX `idx_booking_chairman_email` TO `BOOKING_PLAN_CHAIRMAN_EMAIL_idx`;

-- RenameIndex
ALTER TABLE `BOOKING_PLAN` RENAME INDEX `idx_booking_language_code` TO `BOOKING_PLAN_LANGUAGE_CODE_idx`;

-- RenameIndex
ALTER TABLE `BOOKING_PLAN` RENAME INDEX `idx_booking_selected_interpreter` TO `BOOKING_PLAN_SELECTED_INTERPRETER_EMP_CODE_idx`;
