-- CreateTable (only if not exists)
CREATE TABLE IF NOT EXISTS `ENVIRONMENT_ASSIGNMENT_CONFIG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ENVIRONMENT_ID` INTEGER NOT NULL,
    `MODE` VARCHAR(32) NULL,
    `AUTO_ASSIGN_ENABLED` BOOLEAN NULL,
    `FAIRNESS_WINDOW_DAYS` INTEGER NULL,
    `MAX_GAP_HOURS` INTEGER NULL,
    `W_FAIR` DOUBLE NULL,
    `W_URGENCY` DOUBLE NULL,
    `W_LRS` DOUBLE NULL,
    `DR_CONSECUTIVE_PENALTY` DOUBLE NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE INDEX `ENVIRONMENT_ASSIGNMENT_CONFIG_ENVIRONMENT_ID_key`(`ENVIRONMENT_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey (only if constraint doesn't exist)
SET @exist := (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_SCHEMA = DATABASE() 
               AND TABLE_NAME = 'ENVIRONMENT_ASSIGNMENT_CONFIG' 
               AND CONSTRAINT_NAME = 'ENVIRONMENT_ASSIGNMENT_CONFIG_ENVIRONMENT_ID_fkey');
SET @sqlstmt := IF(@exist = 0, 
    'ALTER TABLE `ENVIRONMENT_ASSIGNMENT_CONFIG` ADD CONSTRAINT `ENVIRONMENT_ASSIGNMENT_CONFIG_ENVIRONMENT_ID_fkey` FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE',
    'SELECT 1');
PREPARE stmt FROM @sqlstmt;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;