-- Backup script for enhanced assignment tables
-- Run this before schema changes to preserve data

-- Backup ENHANCED_ASSIGNMENT_CONFIG
CREATE TABLE IF NOT EXISTS ENHANCED_ASSIGNMENT_CONFIG_BACKUP AS SELECT * FROM ENHANCED_ASSIGNMENT_CONFIG;

-- Backup ASSIGNMENT_POOL  
CREATE TABLE IF NOT EXISTS ASSIGNMENT_POOL_BACKUP AS SELECT * FROM ASSIGNMENT_POOL;

-- Backup CONFIGURATION_CHANGE
CREATE TABLE IF NOT EXISTS CONFIGURATION_CHANGE_BACKUP AS SELECT * FROM CONFIGURATION_CHANGE;

-- Backup ENHANCED_ASSIGNMENT_LOG
CREATE TABLE IF NOT EXISTS ENHANCED_ASSIGNMENT_LOG_BACKUP AS SELECT * FROM ENHANCED_ASSIGNMENT_LOG;

-- Show backup table counts
SELECT 'ENHANCED_ASSIGNMENT_CONFIG_BACKUP' as table_name, COUNT(*) as row_count FROM ENHANCED_ASSIGNMENT_CONFIG_BACKUP
UNION ALL
SELECT 'ASSIGNMENT_POOL_BACKUP', COUNT(*) FROM ASSIGNMENT_POOL_BACKUP  
UNION ALL
SELECT 'CONFIGURATION_CHANGE_BACKUP', COUNT(*) FROM CONFIGURATION_CHANGE_BACKUP
UNION ALL
SELECT 'ENHANCED_ASSIGNMENT_LOG_BACKUP', COUNT(*) FROM ENHANCED_ASSIGNMENT_LOG_BACKUP;