-- CreateTable
CREATE TABLE BOOKING_PLAN (
    BOOKING_ID INTEGER NOT NULL AUTO_INCREMENT,
    OWNER_GROUP ENUM('iot', 'hardware', 'software', 'other') NOT NULL,
    MEETING_ROOM VARCHAR(50) NOT NULL,
    MEETING_DETAIL TEXT NULL,
    TIME_START DATETIME(0) NOT NULL,
    TIME_END DATETIME(0) NOT NULL,
    BOOKING_STATUS ENUM('approve', 'cancel', 'waiting', 'complet') NOT NULL DEFAULT 'waiting',
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    DR_TYPE ENUM('DR-PR', 'DR-k', 'DR-II', 'DR-I', 'Other') NULL,
    OTHER_TYPE VARCHAR(255) NULL,
    OTHER_TYPE_SCOPE ENUM('meeting_type', 'dr_type') NULL,
    APPLICABLE_MODEL VARCHAR(255) NULL,
    INTERPRETER_EMP_CODE VARCHAR(64) NULL,
    IS_RECURRING BOOLEAN NOT NULL DEFAULT false,
    MEETING_TYPE ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL,
    OWNER_EMP_CODE VARCHAR(64) NOT NULL,
    PARENT_BOOKING_ID INTEGER NULL,
    RECURRENCE_END_DATE DATETIME(0) NULL,
    RECURRENCE_END_OCCURRENCES INTEGER NULL,
    RECURRENCE_END_TYPE ENUM('never', 'on_date', 'after_occurrences') NULL,
    RECURRENCE_INTERVAL INTEGER NULL,
    RECURRENCE_MONTHDAY INTEGER NULL,
    RECURRENCE_TYPE ENUM('daily', 'weekly', 'biweekly', 'monthly', 'custom') NULL,
    RECURRENCE_WEEKDAYS VARCHAR(32) NULL,
    RECURRENCE_WEEK_ORDER ENUM('first', 'second', 'third', 'fourth', 'last') NULL,
    FORWARDED_BY_EMP_CODE VARCHAR(64) NULL,
    IS_FORWARDED BOOLEAN NOT NULL DEFAULT false,
    FORWARD_ACTIONS JSON NOT NULL,
    LANGUAGE_CODE VARCHAR(16) NULL,
    CHAIRMAN_EMAIL VARCHAR(255) NULL,
    SELECTED_INTERPRETER_EMP_CODE VARCHAR(64) NULL,
    AUTO_ASSIGN_AT DATETIME(0) NULL,
    AUTO_ASSIGN_ATTEMPTS INTEGER NOT NULL DEFAULT 0,
    AUTO_ASSIGN_LOCKED_AT DATETIME(0) NULL,
    AUTO_ASSIGN_LOCKED_BY VARCHAR(64) NULL,
    AUTO_ASSIGN_STATUS VARCHAR(16) NOT NULL DEFAULT 'pending',

    INDEX BOOKING_PLAN_OWNER_EMP_CODE_idx(OWNER_EMP_CODE),
    INDEX BOOKING_PLAN_INTERPRETER_EMP_CODE_idx(INTERPRETER_EMP_CODE),
    INDEX BOOKING_PLAN_PARENT_BOOKING_ID_idx(PARENT_BOOKING_ID),
    INDEX BOOKING_PLAN_DR_TYPE_idx(DR_TYPE),
    INDEX BOOKING_PLAN_OTHER_TYPE_SCOPE_idx(OTHER_TYPE_SCOPE),
    INDEX BOOKING_PLAN_FORWARDED_BY_EMP_CODE_idx(FORWARDED_BY_EMP_CODE),
    INDEX BOOKING_PLAN_LANGUAGE_CODE_idx(LANGUAGE_CODE),
    INDEX BOOKING_PLAN_CHAIRMAN_EMAIL_idx(CHAIRMAN_EMAIL),
    INDEX BOOKING_PLAN_SELECTED_INTERPRETER_EMP_CODE_idx(SELECTED_INTERPRETER_EMP_CODE),
    INDEX BOOKING_PLAN_AUTO_ASSIGN_STATUS_AUTO_ASSIGN_AT_idx(AUTO_ASSIGN_STATUS, AUTO_ASSIGN_AT),
    PRIMARY KEY (BOOKING_ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE BOOKING_FORWARD_TARGET (
    BOOKING_ID INTEGER NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ENVIRONMENT_ID INTEGER NOT NULL,

    INDEX BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_idx(ENVIRONMENT_ID),
    PRIMARY KEY (BOOKING_ID, ENVIRONMENT_ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE LANGUAGE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(16) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX LANGUAGE_CODE_key(CODE),
    UNIQUE INDEX LANGUAGE_NAME_key(NAME),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE INTERPRETER_LANGUAGE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EMP_CODE VARCHAR(64) NOT NULL,
    LANGUAGE_CODE VARCHAR(16) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX INTERPRETER_LANGUAGE_EMP_CODE_idx(EMP_CODE),
    INDEX INTERPRETER_LANGUAGE_LANGUAGE_CODE_idx(LANGUAGE_CODE),
    UNIQUE INDEX INTERPRETER_LANGUAGE_EMP_CODE_LANGUAGE_CODE_key(EMP_CODE, LANGUAGE_CODE),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE INVITE_EMAIL_LIST (
    EMAIL_LIST_ID INTEGER NOT NULL AUTO_INCREMENT,
    BOOKING_ID INTEGER NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    invited_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX INVITE_EMAIL_LIST_BOOKING_ID_EMAIL_key(BOOKING_ID, EMAIL),
    PRIMARY KEY (EMAIL_LIST_ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE EMPLOYEE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EMP_CODE VARCHAR(64) NOT NULL,
    PREFIX_EN VARCHAR(32) NULL,
    FIRST_NAME_EN VARCHAR(255) NULL,
    LAST_NAME_EN VARCHAR(255) NULL,
    PREFIX_TH VARCHAR(32) NULL,
    FIRST_NAME_TH VARCHAR(255) NULL,
    LAST_NAME_TH VARCHAR(255) NULL,
    FNO VARCHAR(64) NULL,
    DEPT_PATH VARCHAR(512) NULL,
    POSITION_TITLE VARCHAR(255) NULL,
    EMAIL VARCHAR(255) NULL,
    TEL_EXT VARCHAR(64) NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT true,
    LAST_LOGIN_AT DATETIME(3) NULL,
    SYNCED_AT DATETIME(3) NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX EMPLOYEE_EMP_CODE_key(EMP_CODE),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE USER_ROLE (
    USER_ID INTEGER NOT NULL,
    ROLE_CODE ENUM('ADMIN', 'INTERPRETER', 'SUPER_ADMIN') NOT NULL,

    PRIMARY KEY (USER_ID, ROLE_CODE)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE AUTO_ASSIGNMENT_CONFIG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    AUTO_ASSIGN_ENABLED BOOLEAN NOT NULL DEFAULT true,
    MODE VARCHAR(191) NOT NULL DEFAULT 'NORMAL',
    FAIRNESS_WINDOW_DAYS INTEGER NOT NULL DEFAULT 30,
    MAX_GAP_HOURS INTEGER NOT NULL DEFAULT 10,
    MIN_ADVANCE_DAYS INTEGER NOT NULL DEFAULT 2,
    W_FAIR DOUBLE NOT NULL DEFAULT 1.2,
    W_URGENCY DOUBLE NOT NULL DEFAULT 0.5,
    W_LRS DOUBLE NOT NULL DEFAULT 0.3,
    DR_CONSECUTIVE_PENALTY DOUBLE NOT NULL DEFAULT -0.7,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL,
    DAILY_RUN_TIMES VARCHAR(255) NULL,
    POLL_INTERVAL_MINUTES INTEGER NOT NULL DEFAULT 180,
    TIMEZONE VARCHAR(64) NULL,

    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE MEETING_TYPE_PRIORITY (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MEETING_TYPE ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL,
    PRIORITY_VALUE INTEGER NOT NULL,
    URGENT_THRESHOLD_DAYS INTEGER NOT NULL,
    GENERAL_THRESHOLD_DAYS INTEGER NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL,
    ENVIRONMENT_ID INTEGER NULL,

    UNIQUE INDEX MEETING_TYPE_PRIORITY_MEETING_TYPE_key(MEETING_TYPE),
    INDEX MEETING_TYPE_PRIORITY_ENVIRONMENT_ID_fkey(ENVIRONMENT_ID),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE MEETING_TYPE_MODE_THRESHOLD (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MEETING_TYPE ENUM('DR', 'VIP', 'Weekly', 'General', 'Urgent', 'President', 'Other') NOT NULL,
    ASSIGNMENT_MODE VARCHAR(20) NOT NULL,
    URGENT_THRESHOLD_DAYS INTEGER NOT NULL,
    GENERAL_THRESHOLD_DAYS INTEGER NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL,

    UNIQUE INDEX MEETING_TYPE_MODE_THRESHOLD_MEETING_TYPE_ASSIGNMENT_MODE_key(MEETING_TYPE, ASSIGNMENT_MODE),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ENVIRONMENT_ASSIGNMENT_CONFIG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INTEGER NOT NULL,
    MODE VARCHAR(32) NULL,
    AUTO_ASSIGN_ENABLED BOOLEAN NULL,
    FAIRNESS_WINDOW_DAYS INTEGER NULL,
    MAX_GAP_HOURS INTEGER NULL,
    W_FAIR DOUBLE NULL,
    W_URGENCY DOUBLE NULL,
    W_LRS DOUBLE NULL,
    DR_CONSECUTIVE_PENALTY DOUBLE NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX ENVIRONMENT_ASSIGNMENT_CONFIG_ENVIRONMENT_ID_key(ENVIRONMENT_ID),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ASSIGNMENT_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BOOKING_ID INTEGER NOT NULL,
    INTERPRETER_EMP_CODE VARCHAR(64) NULL,
    STATUS VARCHAR(32) NOT NULL,
    REASON TEXT NULL,
    PRE_HOURS_SNAPSHOT JSON NOT NULL,
    POST_HOURS_SNAPSHOT JSON NULL,
    SCORE_BREAKDOWN JSON NULL,
    MAX_GAP_HOURS INTEGER NOT NULL,
    FAIRNESS_WINDOW_DAYS INTEGER NOT NULL,
    CONFLICT_DETECTION JSON NULL,
    DR_POLICY_DECISION JSON NULL,
    PERFORMANCE JSON NULL,
    SYSTEM_STATE JSON NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX ASSIGNMENT_LOG_BOOKING_ID_idx(BOOKING_ID),
    INDEX ASSIGNMENT_LOG_INTERPRETER_EMP_CODE_idx(INTERPRETER_EMP_CODE),
    INDEX ASSIGNMENT_LOG_STATUS_idx(STATUS),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE CONFLICT_DETECTION_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TIMESTAMP DATETIME(0) NOT NULL,
    BOOKING_ID INTEGER NOT NULL,
    REQUESTED_TIME_START DATETIME(0) NOT NULL,
    REQUESTED_TIME_END DATETIME(0) NOT NULL,
    TOTAL_INTERPRETERS_CHECKED INTEGER NOT NULL,
    AVAILABLE_INTERPRETERS INTEGER NOT NULL,
    CONFLICTED_INTERPRETERS INTEGER NOT NULL,
    CONFLICTS JSON NOT NULL,
    PROCESSING_TIME_MS INTEGER NOT NULL,
    RESOLUTION_STRATEGY VARCHAR(64) NOT NULL,
    OUTCOME VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX CONFLICT_DETECTION_LOG_BOOKING_ID_idx(BOOKING_ID),
    INDEX CONFLICT_DETECTION_LOG_TIMESTAMP_idx(TIMESTAMP),
    INDEX CONFLICT_DETECTION_LOG_OUTCOME_idx(OUTCOME),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE DR_POLICY_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TIMESTAMP DATETIME(0) NOT NULL,
    BOOKING_ID INTEGER NOT NULL,
    INTERPRETER_ID VARCHAR(64) NOT NULL,
    IS_DR_MEETING BOOLEAN NOT NULL,
    DR_TYPE VARCHAR(64) NULL,
    MODE VARCHAR(32) NOT NULL,
    POLICY_APPLIED JSON NOT NULL,
    LAST_GLOBAL_DR JSON NULL,
    DR_HISTORY JSON NOT NULL,
    ALTERNATIVE_INTERPRETERS INTEGER NOT NULL,
    FINAL_DECISION VARCHAR(32) NOT NULL,
    DECISION_RATIONALE TEXT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX DR_POLICY_LOG_BOOKING_ID_idx(BOOKING_ID),
    INDEX DR_POLICY_LOG_INTERPRETER_ID_idx(INTERPRETER_ID),
    INDEX DR_POLICY_LOG_TIMESTAMP_idx(TIMESTAMP),
    INDEX DR_POLICY_LOG_FINAL_DECISION_idx(FINAL_DECISION),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE SYSTEM_ERROR_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TIMESTAMP DATETIME(0) NOT NULL,
    OPERATION VARCHAR(128) NOT NULL,
    BOOKING_ID INTEGER NULL,
    ERROR_NAME VARCHAR(128) NOT NULL,
    ERROR_MESSAGE TEXT NOT NULL,
    ERROR_STACK TEXT NULL,
    CONTEXT JSON NULL,
    SYSTEM_STATE JSON NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX SYSTEM_ERROR_LOG_TIMESTAMP_idx(TIMESTAMP),
    INDEX SYSTEM_ERROR_LOG_OPERATION_idx(OPERATION),
    INDEX SYSTEM_ERROR_LOG_BOOKING_ID_idx(BOOKING_ID),
    INDEX SYSTEM_ERROR_LOG_ERROR_NAME_idx(ERROR_NAME),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ENVIRONMENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL,

    UNIQUE INDEX ENVIRONMENT_NAME_key(NAME),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ENVIRONMENT_CENTER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INTEGER NOT NULL,
    CENTER VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX ENVIRONMENT_CENTER_CENTER_key(CENTER),
    INDEX ENVIRONMENT_CENTER_ENVIRONMENT_ID_idx(ENVIRONMENT_ID),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ENVIRONMENT_ADMIN (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INTEGER NOT NULL,
    ADMIN_EMP_CODE VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX ENVIRONMENT_ADMIN_ADMIN_EMP_CODE_idx(ADMIN_EMP_CODE),
    UNIQUE INDEX ENVIRONMENT_ADMIN_ENVIRONMENT_ID_ADMIN_EMP_CODE_key(ENVIRONMENT_ID, ADMIN_EMP_CODE),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ENVIRONMENT_INTERPRETER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID INTEGER NOT NULL,
    INTERPRETER_EMP_CODE VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX ENVIRONMENT_INTERPRETER_INTERPRETER_EMP_CODE_idx(INTERPRETER_EMP_CODE),
    UNIQUE INDEX ENVIRONMENT_INTERPRETER_ENVIRONMENT_ID_INTERPRETER_EMP_CODE_key(ENVIRONMENT_ID, INTERPRETER_EMP_CODE),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ROOM (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LOCATION VARCHAR(255) NULL,
    CAPACITY INTEGER NOT NULL DEFAULT 1,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX UK_ROOM_NAME(NAME),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE ADMIN_VISION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ADMIN_EMP_CODE VARCHAR(64) NOT NULL,
    DEPT_PATH VARCHAR(512) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX ADMIN_VISION_ADMIN_EMP_CODE_idx(ADMIN_EMP_CODE),
    UNIQUE INDEX ADMIN_VISION_ADMIN_EMP_CODE_DEPT_PATH_key(ADMIN_EMP_CODE, DEPT_PATH),
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_FORWARDED_BY_EMP_CODE_fkey FOREIGN KEY (FORWARDED_BY_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_INTERPRETER_EMP_CODE_fkey FOREIGN KEY (INTERPRETER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_LANGUAGE_CODE_fkey FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGE(CODE) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_OWNER_EMP_CODE_fkey FOREIGN KEY (OWNER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_PARENT_BOOKING_ID_fkey FOREIGN KEY (PARENT_BOOKING_ID) REFERENCES BOOKING_PLAN(BOOKING_ID) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_PLAN ADD CONSTRAINT BOOKING_PLAN_SELECTED_INTERPRETER_EMP_CODE_fkey FOREIGN KEY (SELECTED_INTERPRETER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_FORWARD_TARGET ADD CONSTRAINT BOOKING_FORWARD_TARGET_BOOKING_ID_fkey FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_PLAN(BOOKING_ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE BOOKING_FORWARD_TARGET ADD CONSTRAINT BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE INTERPRETER_LANGUAGE ADD CONSTRAINT INTERPRETER_LANGUAGE_EMP_CODE_fkey FOREIGN KEY (EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE INTERPRETER_LANGUAGE ADD CONSTRAINT INTERPRETER_LANGUAGE_LANGUAGE_CODE_fkey FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGE(CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE INVITE_EMAIL_LIST ADD CONSTRAINT INVITE_EMAIL_LIST_BOOKING_ID_fkey FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_PLAN(BOOKING_ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_USER_ID_fkey FOREIGN KEY (USER_ID) REFERENCES EMPLOYEE(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE MEETING_TYPE_PRIORITY ADD CONSTRAINT MEETING_TYPE_PRIORITY_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_ASSIGNMENT_CONFIG ADD CONSTRAINT ENVIRONMENT_ASSIGNMENT_CONFIG_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ASSIGNMENT_LOG ADD CONSTRAINT ASSIGNMENT_LOG_BOOKING_ID_fkey FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_PLAN(BOOKING_ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ASSIGNMENT_LOG ADD CONSTRAINT ASSIGNMENT_LOG_INTERPRETER_EMP_CODE_fkey FOREIGN KEY (INTERPRETER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_CENTER ADD CONSTRAINT ENVIRONMENT_CENTER_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_ADMIN ADD CONSTRAINT ENVIRONMENT_ADMIN_ADMIN_EMP_CODE_fkey FOREIGN KEY (ADMIN_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_ADMIN ADD CONSTRAINT ENVIRONMENT_ADMIN_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_INTERPRETER ADD CONSTRAINT ENVIRONMENT_INTERPRETER_ENVIRONMENT_ID_fkey FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT(ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ENVIRONMENT_INTERPRETER ADD CONSTRAINT ENVIRONMENT_INTERPRETER_INTERPRETER_EMP_CODE_fkey FOREIGN KEY (INTERPRETER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE ADMIN_VISION ADD CONSTRAINT ADMIN_VISION_ADMIN_EMP_CODE_fkey FOREIGN KEY (ADMIN_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

