version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: interpreter-booking-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: interpreter_booking
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: booking_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: devbase
    container_name: interpreter-booking-app
    working_dir: /app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3030
      NEXT_TELEMETRY_DISABLED: "1"
      # Prisma/DB connection to the db service inside the network
      DATABASE_URL: mysql://booking_user:booking_password@db:3306/interpreter_booking
      # Reliable file watching inside containers on Windows/Mac
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_INTERVAL: "200"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    command: >-
      sh -c "(npm ci || npm install) && npx prisma migrate deploy && npm run dev"

volumes:
  db_data:
  node_modules:
  next_cache:
