/*
  Warnings:

  - You are about to drop the column `HIGH_PRIORITY` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `INTERPRETER_ID` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `OWNER_EMAIL` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `OWNER_NAME` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `OWNER_SURNAME` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `OWNER_TEL` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `skip_weekends` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the `ADMIN` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `INTERPRETER` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `MEETING_TYPE` to the `BOOKING_PLAN` table without a default value. This is not possible if the table is not empty.
  - Added the required column `OWNER_EMP_CODE` to the `BOOKING_PLAN` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE `BOOKING_PLAN` DROP FOREIGN KEY `BOOKING_PLAN_INTERPRETER_ID_fkey`;

-- DropIndex
DROP INDEX `BOOKING_PLAN_INTERPRETER_ID_fkey` ON `BOOKING_PLAN`;

-- AlterTable
ALTER TABLE `BOOKING_PLAN` DROP COLUMN `HIGH_PRIORITY`,
    DROP COLUMN `INTERPRETER_ID`,
    DROP COLUMN `OWNER_EMAIL`,
    DROP COLUMN `OWNER_NAME`,
    DROP COLUMN `OWNER_SURNAME`,
    DROP COLUMN `OWNER_TEL`,
    DROP COLUMN `skip_weekends`,
    ADD COLUMN `APPLICABLE_MODEL` VARCHAR(255) NULL,
    ADD COLUMN `INTERPRETER_EMP_CODE` VARCHAR(64) NULL,
    ADD COLUMN `IS_RECURRING` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `MEETING_TYPE` ENUM('DR', 'VIP', 'Weekly', 'General', 'Augent', 'Other') NOT NULL,
    ADD COLUMN `OWNER_EMP_CODE` VARCHAR(64) NOT NULL,
    ADD COLUMN `PARENT_BOOKING_ID` INTEGER NULL,
    ADD COLUMN `POOL_DEADLINE_TIME` DATETIME(0) NULL,
    ADD COLUMN `POOL_ENTRY_TIME` DATETIME(0) NULL,
    ADD COLUMN `POOL_PROCESSING_ATTEMPTS` INTEGER NULL DEFAULT 0,
    ADD COLUMN `POOL_STATUS` ENUM('waiting', 'ready', 'processing', 'failed') NULL,
    ADD COLUMN `RECURRENCE_END_DATE` DATETIME(0) NULL,
    ADD COLUMN `RECURRENCE_END_OCCURRENCES` INTEGER NULL,
    ADD COLUMN `RECURRENCE_END_TYPE` ENUM('never', 'on_date', 'after_occurrences') NULL,
    ADD COLUMN `RECURRENCE_INTERVAL` INTEGER NULL,
    ADD COLUMN `RECURRENCE_MONTHDAY` INTEGER NULL,
    ADD COLUMN `RECURRENCE_TYPE` ENUM('daily', 'weekly', 'biweekly', 'monthly', 'custom') NULL,
    ADD COLUMN `RECURRENCE_WEEKDAYS` VARCHAR(32) NULL,
    ADD COLUMN `RECURRENCE_WEEK_ORDER` ENUM('first', 'second', 'third', 'fourth', 'last') NULL,
    MODIFY `BOOKING_STATUS` ENUM('approve', 'cancel', 'waiting', 'complet') NOT NULL DEFAULT 'waiting';

-- DropTable
DROP TABLE `ADMIN`;

-- DropTable
DROP TABLE `INTERPRETER`;

-- CreateTable
CREATE TABLE `EMPLOYEE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EMP_CODE` VARCHAR(64) NOT NULL,
    `PREFIX_EN` VARCHAR(32) NULL,
    `FIRST_NAME_EN` VARCHAR(255) NULL,
    `LAST_NAME_EN` VARCHAR(255) NULL,
    `PREFIX_TH` VARCHAR(32) NULL,
    `FIRST_NAME_TH` VARCHAR(255) NULL,
    `LAST_NAME_TH` VARCHAR(255) NULL,
    `FNO` VARCHAR(64) NULL,
    `DEPT_PATH` VARCHAR(512) NULL,
    `POSITION_TITLE` VARCHAR(255) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `TEL_EXT` VARCHAR(64) NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `LAST_LOGIN_AT` DATETIME(3) NULL,
    `SYNCED_AT` DATETIME(3) NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `EMPLOYEE_EMP_CODE_key`(`EMP_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_ROLE` (
    `USER_ID` INTEGER NOT NULL,
    `ROLE_CODE` ENUM('ADMIN', 'INTERPRETER') NOT NULL,

    PRIMARY KEY (`USER_ID`, `ROLE_CODE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AUTO_ASSIGNMENT_CONFIG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `AUTO_ASSIGN_ENABLED` BOOLEAN NOT NULL DEFAULT true,
    `MODE` VARCHAR(191) NOT NULL DEFAULT 'NORMAL',
    `FAIRNESS_WINDOW_DAYS` INTEGER NOT NULL DEFAULT 30,
    `MAX_GAP_HOURS` INTEGER NOT NULL DEFAULT 10,
    `MIN_ADVANCE_DAYS` INTEGER NOT NULL DEFAULT 2,
    `W_FAIR` DOUBLE NOT NULL DEFAULT 1.2,
    `W_URGENCY` DOUBLE NOT NULL DEFAULT 0.5,
    `W_LRS` DOUBLE NOT NULL DEFAULT 0.3,
    `DR_CONSECUTIVE_PENALTY` DOUBLE NOT NULL DEFAULT -0.7,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MEETING_TYPE_PRIORITY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MEETING_TYPE` ENUM('DR', 'VIP', 'Weekly', 'General', 'Augent', 'Other') NOT NULL,
    `PRIORITY_VALUE` INTEGER NOT NULL,
    `URGENT_THRESHOLD_DAYS` INTEGER NOT NULL,
    `GENERAL_THRESHOLD_DAYS` INTEGER NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL,

    UNIQUE INDEX `MEETING_TYPE_PRIORITY_MEETING_TYPE_key`(`MEETING_TYPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ASSIGNMENT_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BOOKING_ID` INTEGER NOT NULL,
    `INTERPRETER_EMP_CODE` VARCHAR(64) NULL,
    `STATUS` VARCHAR(32) NOT NULL,
    `REASON` TEXT NULL,
    `PRE_HOURS_SNAPSHOT` JSON NOT NULL,
    `POST_HOURS_SNAPSHOT` JSON NULL,
    `SCORE_BREAKDOWN` JSON NULL,
    `MAX_GAP_HOURS` INTEGER NOT NULL,
    `FAIRNESS_WINDOW_DAYS` INTEGER NOT NULL,
    `CONFLICT_DETECTION` JSON NULL,
    `DR_POLICY_DECISION` JSON NULL,
    `PERFORMANCE` JSON NULL,
    `POOL_PROCESSING` JSON NULL,
    `SYSTEM_STATE` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ASSIGNMENT_LOG_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `ASSIGNMENT_LOG_INTERPRETER_EMP_CODE_idx`(`INTERPRETER_EMP_CODE`),
    INDEX `ASSIGNMENT_LOG_STATUS_idx`(`STATUS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `POOL_PROCESSING_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BATCH_ID` VARCHAR(255) NOT NULL,
    `PROCESSING_TYPE` VARCHAR(32) NOT NULL,
    `MODE` VARCHAR(32) NULL,
    `PROCESSING_START_TIME` DATETIME(0) NOT NULL,
    `PROCESSING_END_TIME` DATETIME(0) NOT NULL,
    `TOTAL_ENTRIES` INTEGER NOT NULL,
    `PROCESSED_ENTRIES` INTEGER NOT NULL,
    `ASSIGNED_ENTRIES` INTEGER NOT NULL,
    `ESCALATED_ENTRIES` INTEGER NOT NULL,
    `FAILED_ENTRIES` INTEGER NOT NULL,
    `AVERAGE_PROCESSING_TIME_MS` INTEGER NOT NULL,
    `SYSTEM_LOAD` VARCHAR(16) NOT NULL,
    `FAIRNESS_IMPROVEMENT` DOUBLE NULL,
    `ERRORS` JSON NOT NULL,
    `PERFORMANCE` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `POOL_PROCESSING_LOG_BATCH_ID_key`(`BATCH_ID`),
    INDEX `POOL_PROCESSING_LOG_PROCESSING_TYPE_idx`(`PROCESSING_TYPE`),
    INDEX `POOL_PROCESSING_LOG_PROCESSING_START_TIME_idx`(`PROCESSING_START_TIME`),
    INDEX `POOL_PROCESSING_LOG_BATCH_ID_idx`(`BATCH_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `POOL_PROCESSING_LOG_ENTRY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOG_ID` INTEGER NOT NULL,
    `BOOKING_ID` INTEGER NOT NULL,
    `STATUS` VARCHAR(32) NOT NULL,
    `INTERPRETER_ID` VARCHAR(64) NULL,
    `REASON` TEXT NULL,
    `PROCESSING_TIME_MS` INTEGER NOT NULL,
    `URGENCY_LEVEL` VARCHAR(16) NOT NULL,
    `ERROR_RECOVERY` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `POOL_PROCESSING_LOG_ENTRY_LOG_ID_idx`(`LOG_ID`),
    INDEX `POOL_PROCESSING_LOG_ENTRY_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `POOL_PROCESSING_LOG_ENTRY_STATUS_idx`(`STATUS`),
    INDEX `POOL_PROCESSING_LOG_ENTRY_URGENCY_LEVEL_idx`(`URGENCY_LEVEL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `POOL_ENTRY_HISTORY` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BOOKING_ID` INTEGER NOT NULL,
    `ACTION` VARCHAR(64) NOT NULL,
    `PREVIOUS_STATUS` VARCHAR(32) NULL,
    `NEW_STATUS` VARCHAR(32) NULL,
    `PROCESSING_ATTEMPTS` INTEGER NOT NULL,
    `ERROR_MESSAGE` TEXT NULL,
    `SYSTEM_STATE` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `POOL_ENTRY_HISTORY_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `POOL_ENTRY_HISTORY_ACTION_idx`(`ACTION`),
    INDEX `POOL_ENTRY_HISTORY_created_at_idx`(`created_at`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AUTO_APPROVAL_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TIMESTAMP` DATETIME(0) NOT NULL,
    `EVENT_TYPE` VARCHAR(64) NOT NULL,
    `REASON` TEXT NOT NULL,
    `OLD_MODE` VARCHAR(32) NULL,
    `NEW_MODE` VARCHAR(32) NULL,
    `CURRENT_MODE` VARCHAR(32) NOT NULL,
    `LOAD_ASSESSMENT` JSON NULL,
    `CONFIDENCE` DOUBLE NULL,
    `OVERRIDE_APPLIED` BOOLEAN NOT NULL DEFAULT false,
    `EXPIRES_AT` DATETIME(0) NULL,
    `MODE_TRANSITION` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `AUTO_APPROVAL_LOG_TIMESTAMP_idx`(`TIMESTAMP`),
    INDEX `AUTO_APPROVAL_LOG_EVENT_TYPE_idx`(`EVENT_TYPE`),
    INDEX `AUTO_APPROVAL_LOG_CURRENT_MODE_idx`(`CURRENT_MODE`),
    INDEX `AUTO_APPROVAL_LOG_OVERRIDE_APPLIED_idx`(`OVERRIDE_APPLIED`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CONFLICT_DETECTION_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TIMESTAMP` DATETIME(0) NOT NULL,
    `BOOKING_ID` INTEGER NOT NULL,
    `REQUESTED_TIME_START` DATETIME(0) NOT NULL,
    `REQUESTED_TIME_END` DATETIME(0) NOT NULL,
    `TOTAL_INTERPRETERS_CHECKED` INTEGER NOT NULL,
    `AVAILABLE_INTERPRETERS` INTEGER NOT NULL,
    `CONFLICTED_INTERPRETERS` INTEGER NOT NULL,
    `CONFLICTS` JSON NOT NULL,
    `PROCESSING_TIME_MS` INTEGER NOT NULL,
    `RESOLUTION_STRATEGY` VARCHAR(64) NOT NULL,
    `OUTCOME` VARCHAR(32) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `CONFLICT_DETECTION_LOG_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `CONFLICT_DETECTION_LOG_TIMESTAMP_idx`(`TIMESTAMP`),
    INDEX `CONFLICT_DETECTION_LOG_OUTCOME_idx`(`OUTCOME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DR_POLICY_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TIMESTAMP` DATETIME(0) NOT NULL,
    `BOOKING_ID` INTEGER NOT NULL,
    `INTERPRETER_ID` VARCHAR(64) NOT NULL,
    `IS_DR_MEETING` BOOLEAN NOT NULL,
    `DR_TYPE` VARCHAR(64) NULL,
    `MODE` VARCHAR(32) NOT NULL,
    `POLICY_APPLIED` JSON NOT NULL,
    `LAST_GLOBAL_DR` JSON NULL,
    `DR_HISTORY` JSON NOT NULL,
    `ALTERNATIVE_INTERPRETERS` INTEGER NOT NULL,
    `FINAL_DECISION` VARCHAR(32) NOT NULL,
    `DECISION_RATIONALE` TEXT NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `DR_POLICY_LOG_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `DR_POLICY_LOG_INTERPRETER_ID_idx`(`INTERPRETER_ID`),
    INDEX `DR_POLICY_LOG_TIMESTAMP_idx`(`TIMESTAMP`),
    INDEX `DR_POLICY_LOG_FINAL_DECISION_idx`(`FINAL_DECISION`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SYSTEM_ERROR_LOG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TIMESTAMP` DATETIME(0) NOT NULL,
    `OPERATION` VARCHAR(128) NOT NULL,
    `BOOKING_ID` INTEGER NULL,
    `ERROR_NAME` VARCHAR(128) NOT NULL,
    `ERROR_MESSAGE` TEXT NOT NULL,
    `ERROR_STACK` TEXT NULL,
    `CONTEXT` JSON NULL,
    `SYSTEM_STATE` JSON NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `SYSTEM_ERROR_LOG_TIMESTAMP_idx`(`TIMESTAMP`),
    INDEX `SYSTEM_ERROR_LOG_OPERATION_idx`(`OPERATION`),
    INDEX `SYSTEM_ERROR_LOG_BOOKING_ID_idx`(`BOOKING_ID`),
    INDEX `SYSTEM_ERROR_LOG_ERROR_NAME_idx`(`ERROR_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_OWNER_EMP_CODE_idx` ON `BOOKING_PLAN`(`OWNER_EMP_CODE`);

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_INTERPRETER_EMP_CODE_idx` ON `BOOKING_PLAN`(`INTERPRETER_EMP_CODE`);

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_PARENT_BOOKING_ID_idx` ON `BOOKING_PLAN`(`PARENT_BOOKING_ID`);

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_POOL_STATUS_idx` ON `BOOKING_PLAN`(`POOL_STATUS`);

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_POOL_DEADLINE_TIME_idx` ON `BOOKING_PLAN`(`POOL_DEADLINE_TIME`);

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_POOL_STATUS_POOL_DEADLINE_TIME_idx` ON `BOOKING_PLAN`(`POOL_STATUS`, `POOL_DEADLINE_TIME`);

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_INTERPRETER_EMP_CODE_fkey` FOREIGN KEY (`INTERPRETER_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_OWNER_EMP_CODE_fkey` FOREIGN KEY (`OWNER_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_PARENT_BOOKING_ID_fkey` FOREIGN KEY (`PARENT_BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_ROLE` ADD CONSTRAINT `USER_ROLE_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `EMPLOYEE`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ASSIGNMENT_LOG` ADD CONSTRAINT `ASSIGNMENT_LOG_BOOKING_ID_fkey` FOREIGN KEY (`BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ASSIGNMENT_LOG` ADD CONSTRAINT `ASSIGNMENT_LOG_INTERPRETER_EMP_CODE_fkey` FOREIGN KEY (`INTERPRETER_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `POOL_PROCESSING_LOG_ENTRY` ADD CONSTRAINT `POOL_PROCESSING_LOG_ENTRY_LOG_ID_fkey` FOREIGN KEY (`LOG_ID`) REFERENCES `POOL_PROCESSING_LOG`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `POOL_PROCESSING_LOG_ENTRY` ADD CONSTRAINT `POOL_PROCESSING_LOG_ENTRY_BOOKING_ID_fkey` FOREIGN KEY (`BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `POOL_ENTRY_HISTORY` ADD CONSTRAINT `POOL_ENTRY_HISTORY_BOOKING_ID_fkey` FOREIGN KEY (`BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
