-- Migrate BOOKING_FORWARD_TARGET from DEPT_PATH to ENVIRONMENT_ID
-- 1) Add ENVIRONMENT_ID (nullable temporarily)
-- 1) Add ENVIRONMENT_ID if not already there (MySQL 5.7 compatible)
SET @has_col = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'BOOKING_FORWARD_TARGET'
    AND COLUMN_NAME = 'ENVIRONMENT_ID'
);
SET @sql_add_col = IF(@has_col = 0,
  'ALTER TABLE `BOOKING_FORWARD_TARGET` ADD COLUMN `ENVIRONMENT_ID` INT NULL',
  'SELECT 1'
);
PREPARE s0 FROM @sql_add_col; EXECUTE s0; DEALLOCATE PREPARE s0;

-- 2) Populate ENVIRONMENT_ID by joining center name to ENVIRONMENT_CENTER
UPDATE `BOOKING_FORWARD_TARGET` bft
JOIN `ENVIRONMENT_CENTER` ec ON ec.`CENTER` = bft.`DEPT_PATH`
SET bft.`ENVIRONMENT_ID` = ec.`ENVIRONMENT_ID`;

-- 2.1) If any rows cannot be mapped, remove them to allow NOT NULL constraint
--      (forward targets are ephemeral; admins can re-forward if needed)
DELETE FROM `BOOKING_FORWARD_TARGET` WHERE `ENVIRONMENT_ID` IS NULL;

-- 3) Drop existing PK and DEPT_PATH index
-- 3) Drop existing PK and legacy index (if present)
SET @has_pk = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'BOOKING_FORWARD_TARGET'
    AND CONSTRAINT_TYPE = 'PRIMARY KEY'
);
SET @sql_drop_pk = IF(@has_pk > 0,
  'ALTER TABLE `BOOKING_FORWARD_TARGET` DROP PRIMARY KEY',
  'SELECT 1'
);
PREPARE spk FROM @sql_drop_pk; EXECUTE spk; DEALLOCATE PREPARE spk;
SET @has_old_idx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'BOOKING_FORWARD_TARGET'
    AND INDEX_NAME = 'BOOKING_FORWARD_TARGET_DEPT_PATH_idx'
);
SET @sql_drop_old_idx = IF(@has_old_idx > 0,
  'DROP INDEX `BOOKING_FORWARD_TARGET_DEPT_PATH_idx` ON `BOOKING_FORWARD_TARGET`',
  'SELECT 1'
);
PREPARE s1 FROM @sql_drop_old_idx; EXECUTE s1; DEALLOCATE PREPARE s1;

-- 4) Make ENVIRONMENT_ID NOT NULL
ALTER TABLE `BOOKING_FORWARD_TARGET` MODIFY `ENVIRONMENT_ID` INT NOT NULL;

-- 5) Add new PK and index + FK
ALTER TABLE `BOOKING_FORWARD_TARGET`
  ADD PRIMARY KEY (`BOOKING_ID`, `ENVIRONMENT_ID`);

-- Create envId index if missing
SET @has_env_idx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'BOOKING_FORWARD_TARGET'
    AND INDEX_NAME = 'BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_idx'
);
SET @sql_create_env_idx = IF(@has_env_idx = 0,
  'CREATE INDEX `BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_idx` ON `BOOKING_FORWARD_TARGET`(`ENVIRONMENT_ID`)',
  'SELECT 1'
);
PREPARE s2 FROM @sql_create_env_idx; EXECUTE s2; DEALLOCATE PREPARE s2;

-- Add FK if missing
SET @has_fk = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE()
    AND CONSTRAINT_NAME = 'BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_fkey'
);
SET @sql_add_fk = IF(@has_fk = 0,
  'ALTER TABLE `BOOKING_FORWARD_TARGET`\n  ADD CONSTRAINT `BOOKING_FORWARD_TARGET_ENVIRONMENT_ID_fkey`\n  FOREIGN KEY (`ENVIRONMENT_ID`) REFERENCES `ENVIRONMENT`(`ID`)\n  ON DELETE CASCADE ON UPDATE CASCADE',
  'SELECT 1'
);
PREPARE s3 FROM @sql_add_fk; EXECUTE s3; DEALLOCATE PREPARE s3;

-- 6) Drop legacy DEPT_PATH column
-- 6) Drop legacy DEPT_PATH column (if present) - MySQL 5.7 compatible
SET @has_dept = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'BOOKING_FORWARD_TARGET'
    AND COLUMN_NAME = 'DEPT_PATH'
);
SET @sql_drop_dept = IF(@has_dept > 0,
  'ALTER TABLE `BOOKING_FORWARD_TARGET` DROP COLUMN `DEPT_PATH`',
  'SELECT 1'
);
PREPARE s4 FROM @sql_drop_dept; EXECUTE s4; DEALLOCATE PREPARE s4;
