/*
  Warnings:

  - You are about to drop the column `FORWARDED_AT` on the `BOOKING_PLAN` table. All the data in the column will be lost.
  - You are about to drop the column `FORWARD_NOTE` on the `BOOKING_PLAN` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `BOOKING_PLAN` DROP COLUMN `FORWARDED_AT`,
    DROP COLUMN `FORWARD_NOTE`,
    ADD COLUMN `FORWARD_ACTIONS` JSON NOT NULL;

-- CreateTable
CREATE TABLE `BOOKING_FORWARD_TARGET` (
    `BOOKING_ID` INTEGER NOT NULL,
    `DEPT_PATH` VARCHAR(512) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `BOOKING_FORWARD_TARGET_DEPT_PATH_idx`(`DEPT_PATH`),
    PRIMARY KEY (`BOOKING_ID`, `DEPT_PATH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BOOKING_FORWARD_TARGET` ADD CONSTRAINT `BOOKING_FORWARD_TARGET_BOOKING_ID_fkey` FOREIGN KEY (`BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
