-- AlterTable
ALTER TABLE `BOOKING_PLAN` ADD COLUMN `FORWARDED_AT` DATETIME(0) NULL,
    ADD COLUMN `FORWARDED_BY_EMP_CODE` VARCHAR(64) NULL,
    ADD COLUMN `FORWARD_NOTE` VARCHAR(255) NULL,
    ADD COLUMN `IS_FORWARDED` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `LANGUAGE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(16) NOT NULL,
    `NAME` VARCHAR(128) NOT NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `LANGUAGE_CODE_key`(`CODE`),
    UNIQUE INDEX `LANGUAGE_NAME_key`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INTERPRETER_LANGUAGE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EMP_CODE` VARCHAR(64) NOT NULL,
    `LANGUAGE_CODE` VARCHAR(16) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `INTERPRETER_LANGUAGE_EMP_CODE_idx`(`EMP_CODE`),
    INDEX `INTERPRETER_LANGUAGE_LANGUAGE_CODE_idx`(`LANGUAGE_CODE`),
    UNIQUE INDEX `INTERPRETER_LANGUAGE_EMP_CODE_LANGUAGE_CODE_key`(`EMP_CODE`, `LANGUAGE_CODE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ADMIN_VISION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADMIN_EMP_CODE` VARCHAR(64) NOT NULL,
    `DEPT_PATH` VARCHAR(512) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ADMIN_VISION_ADMIN_EMP_CODE_idx`(`ADMIN_EMP_CODE`),
    UNIQUE INDEX `ADMIN_VISION_ADMIN_EMP_CODE_DEPT_PATH_key`(`ADMIN_EMP_CODE`, `DEPT_PATH`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `BOOKING_PLAN_FORWARDED_BY_EMP_CODE_idx` ON `BOOKING_PLAN`(`FORWARDED_BY_EMP_CODE`);

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_FORWARDED_BY_EMP_CODE_fkey` FOREIGN KEY (`FORWARDED_BY_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INTERPRETER_LANGUAGE` ADD CONSTRAINT `INTERPRETER_LANGUAGE_EMP_CODE_fkey` FOREIGN KEY (`EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INTERPRETER_LANGUAGE` ADD CONSTRAINT `INTERPRETER_LANGUAGE_LANGUAGE_CODE_fkey` FOREIGN KEY (`LANGUAGE_CODE`) REFERENCES `LANGUAGE`(`CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ADMIN_VISION` ADD CONSTRAINT `ADMIN_VISION_ADMIN_EMP_CODE_fkey` FOREIGN KEY (`ADMIN_EMP_CODE`) REFERENCES `EMPLOYEE`(`EMP_CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;
