-- CreateTable
CREATE TABLE "MEETING_TYPE_PRIORITY" (
    "ID" SERIAL NOT NULL,
    "MEETING_TYPE" TEXT NOT NULL,
    "PRIORITY_VALUE" INTEGER NOT NULL,
    "URGENT_THRESHOLD_DAYS" INTEGER NOT NULL,
    "GENERAL_THRESHOLD_DAYS" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) NOT NULL,

    CONSTRAINT "MEETING_TYPE_PRIORITY_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "MEETING_TYPE_PRIORITY_MEETING_TYPE_key" ON "MEETING_TYPE_PRIORITY"("MEETING_TYPE");

-- AlterTable
ALTER TABLE "AUTO_ASSIGNMENT_CONFIG" ADD COLUMN "MODE" TEXT NOT NULL DEFAULT 'NORMAL';

-- Insert default meeting type priorities
INSERT INTO "MEETING_TYPE_PRIORITY" ("MEETING_TYPE", "PRIORITY_VALUE", "URGENT_THRESHOLD_DAYS", "GENERAL_THRESHOLD_DAYS") VALUES
('DR', 5, 1, 7),
('VIP', 4, 2, 14),
('Weekly', 3, 3, 21),
('General', 2, 3, 30),
('Augent', 2, 3, 30),
('Other', 1, 5, 45);
