-- CreateTable
CREATE TABLE `ADMIN` (
    `ADMIN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADMIN_NAME` VARCHAR(255) NOT NULL,
    `ADMIN_SURNAME` VARCHAR(255) NOT NULL,
    `ADMIN_EMAIL` VARCHAR(255) NOT NULL,
    `USERNAME` VARCHAR(40) NOT NULL,
    `PASSWORD` VARCHAR(60) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `ADMIN_USERNAME_key`(`USERNAME`),
    PRIMARY KEY (`ADMIN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INTERPRETER` (
    `INTERPRETER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `INTERPRETER_NAME` VARCHAR(255) NOT NULL,
    `INTERPRETER_SURNAME` VARCHAR(255) NOT NULL,
    `INTERPRETER_PHONE` VARCHAR(15) NOT NULL,
    `INTERPRETER_EMAIL` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `INTERPRETER_INTERPRETER_EMAIL_key`(`INTERPRETER_EMAIL`),
    PRIMARY KEY (`INTERPRETER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BOOKING_PLAN` (
    `BOOKING_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OWNER_NAME` VARCHAR(255) NOT NULL,
    `OWNER_SURNAME` VARCHAR(255) NOT NULL,
    `OWNER_EMAIL` VARCHAR(255) NOT NULL,
    `OWNER_TEL` VARCHAR(15) NOT NULL,
    `OWNER_GROUP` ENUM('iot', 'hardware', 'software', 'other') NOT NULL,
    `MEETING_ROOM` VARCHAR(50) NOT NULL,
    `MEETING_DETAIL` TEXT NULL,
    `HIGH_PRIORITY` BOOLEAN NOT NULL DEFAULT false,
    `TIME_START` DATETIME(0) NOT NULL,
    `TIME_END` DATETIME(0) NOT NULL,
    `INTERPRETER_ID` INTEGER NULL,
    `BOOKING_STATUS` ENUM('approve', 'cancel', 'waiting') NOT NULL DEFAULT 'waiting',
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`BOOKING_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVITE_EMAIL_LIST` (
    `EMAIL_LIST_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BOOKING_ID` INTEGER NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `invited_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `INVITE_EMAIL_LIST_BOOKING_ID_EMAIL_key`(`BOOKING_ID`, `EMAIL`),
    PRIMARY KEY (`EMAIL_LIST_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BOOKING_PLAN` ADD CONSTRAINT `BOOKING_PLAN_INTERPRETER_ID_fkey` FOREIGN KEY (`INTERPRETER_ID`) REFERENCES `INTERPRETER`(`INTERPRETER_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVITE_EMAIL_LIST` ADD CONSTRAINT `INVITE_EMAIL_LIST_BOOKING_ID_fkey` FOREIGN KEY (`BOOKING_ID`) REFERENCES `BOOKING_PLAN`(`BOOKING_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
