-- Migration script for Interpreter Auto-Assignment System
-- Run this after updating the Prisma schema

-- Create AutoAssignmentConfig table
CREATE TABLE IF NOT EXISTS AUTO_ASSIGNMENT_CONFIG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTO_ASSIGN_ENABLED BOOLEAN DEFAULT TRUE,
  FAIRNESS_WINDOW_DAYS INT DEFAULT 30,
  MAX_GAP_HOURS INT DEFAULT 10,
  MIN_ADVANCE_DAYS INT DEFAULT 2,
  W_FAIR FLOAT DEFAULT 1.2,
  W_URGENCY FLOAT DEFAULT 0.5,
  W_LRS FLOAT DEFAULT 0.3,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create AssignmentLog table
CREATE TABLE IF NOT EXISTS ASSIGNMENT_LOG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BOOKING_ID INT NOT NULL,
  INTERPRETER_EMP_CODE VARCHAR(64),
  STATUS VARCHAR(32) NOT NULL,
  REASON TEXT,
  PRE_HOURS_SNAPSHOT JSON NOT NULL,
  POST_HOURS_SNAPSHOT JSON,
  SCORE_BREAKDOWN JSON,
  MAX_GAP_HOURS INT NOT NULL,
  FAIRNESS_WINDOW_DAYS INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  INDEX BOOKING_ID_idx (BOOKING_ID),
  INDEX INTERPRETER_EMP_CODE_idx (INTERPRETER_EMP_CODE),
  INDEX STATUS_idx (STATUS),
  
  FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_PLAN(BOOKING_ID) ON DELETE CASCADE,
  FOREIGN KEY (INTERPRETER_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE)
);

-- Seed initial configuration
INSERT INTO AUTO_ASSIGNMENT_CONFIG (
  AUTO_ASSIGN_ENABLED,
  FAIRNESS_WINDOW_DAYS,
  MAX_GAP_HOURS,
  MIN_ADVANCE_DAYS,
  W_FAIR,
  W_URGENCY,
  W_LRS
) VALUES (
  TRUE,   -- Auto-assignment enabled by default
  30,     -- 30-day rolling window
  10,     -- Max 10 hour gap
  2,      -- Urgency starts 2 days before
  1.2,    -- Fairness weight
  0.5,    -- Urgency weight
  0.3     -- LRS weight
) ON DUPLICATE KEY UPDATE ID = ID;

-- Verify tables were created
SELECT 'AutoAssignmentConfig' as table_name, COUNT(*) as row_count FROM AUTO_ASSIGNMENT_CONFIG
UNION ALL
SELECT 'AssignmentLog' as table_name, COUNT(*) as row_count FROM ASSIGNMENT_LOG;

-- Show initial configuration
SELECT * FROM AUTO_ASSIGNMENT_CONFIG;
